name: coder_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/Background Main_Dark Mode_No Scroll.png

fonts:
  - family: LuckiestGuy
    fonts:
      - asset: assets/fonts/LuckiestGuy-Regular.ttf
