// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWTk6xVflplfTW0WC20XwAFifXiGEqPPU',
    appId: '1:895631105665:android:4ba18d782eb88a8a4ab780',
    messagingSenderId: '895631105665',
    projectId: 'coder-329a8',
    storageBucket: 'coder-329a8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yEjQvOnaCoJz1hbpYkDKN22Ch_X4jrM',
    appId: '1:895631105665:web:1282c6fac6b2c0c94ab780',
    messagingSenderId: '895631105665',
    projectId: 'coder-329a8',
    authDomain: 'coder-329a8.firebaseapp.com',
    storageBucket: 'coder-329a8.firebasestorage.app',
    measurementId: 'G-XMGBRFE4L0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQdJE7TcvQdfUYxdlavHsyKjpN7s-EuTE',
    appId: '1:895631105665:ios:1c3566547a21427f4ab780',
    messagingSenderId: '895631105665',
    projectId: 'coder-329a8',
    storageBucket: 'coder-329a8.firebasestorage.app',
    iosBundleId: 'com.example.coderApplication',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQdJE7TcvQdfUYxdlavHsyKjpN7s-EuTE',
    appId: '1:895631105665:ios:1c3566547a21427f4ab780',
    messagingSenderId: '895631105665',
    projectId: 'coder-329a8',
    storageBucket: 'coder-329a8.firebasestorage.app',
    iosBundleId: 'com.example.coderApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5yEjQvOnaCoJz1hbpYkDKN22Ch_X4jrM',
    appId: '1:895631105665:web:2f8e37da0a1924b94ab780',
    messagingSenderId: '895631105665',
    projectId: 'coder-329a8',
    authDomain: 'coder-329a8.firebaseapp.com',
    storageBucket: 'coder-329a8.firebasestorage.app',
    measurementId: 'G-LF0YH7NFEJ',
  );

}